[project]
name = "django-money-flow"
version = "0.1.0"
description = ""
authors = [{ name = "Maxim Sytdikov" }]
requires-python = "~=3.13"
readme = "README.md"
dependencies = [
    "django>=5.1.1,<6",
    "django-extensions>=3.2.3,<4",
    "python-dotenv>=1.0.1,<2",
    "django-imagekit>=5.0.0,<6",
    "django-filter~=24.3",
    "django-crispy-forms~=2.3",
    "crispy-bootstrap5~=2024.10",
    "django-debug-toolbar>=4.4.6,<5",
    "django-otp>=1.5.4,<2",
    "pyotp>=2.9.0,<3",
    "fastapi>=0.115.5,<0.116",
    "phonenumberslite>=8.13.50,<9",
    "psycopg2-binary>=2.9.10,<3",
    "django-leaflet>=0.31.0,<0.32",
    "celery>=5.5.1,<6",
    "django-redis>=5.4.0,<6",
    "python-decouple~=3.8",
    "rich>=14.0.0,<15",
    "django-mptt>=0.17.0",
]
