# Generated by Django 5.1.1 on 2025-07-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_remove_category_unique_parent_slug_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='money_flows_types',
        ),
        migrations.AddField(
            model_name='user',
            name='money_flows_statuses',
            field=models.ManyToManyField(blank=True, related_name='users', to='finances.moneyflowstatus', verbose_name='Money flow statuses'),
        ),
        migrations.AlterField(
            model_name='user',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='users', to='finances.category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='user',
            name='category_types',
            field=models.ManyToManyField(blank=True, related_name='users', to='finances.categorytype', verbose_name='Category type'),
        ),
    ]
