# Generated by Django 5.1.1 on 2025-07-25 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_money_flows_types_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='money_flows_statuses',
            new_name='money_flow_statuses',
        ),
    ]
