# Generated by Django 5.1.1 on 2025-07-25 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_money_flows_statuses_user_money_flow_statuses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='user',
            name='category_types',
        ),
        migrations.RemoveField(
            model_name='user',
            name='money_flow_statuses',
        ),
    ]
