# Generated by Django 5.1.1 on 2025-07-27 08:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('finances', '0001_initial'), ('finances', '0002_moneyflow_status_moneyflow_user_and_more'), ('finances', '0003_remove_category_unique_parent_slug_and_more'), ('finances', '0004_category_user_categorytype_user_moneyflowstatus_user'), ('finances', '0005_alter_category_title_alter_categorytype_title_and_more'), ('finances', '0006_alter_category_parent_alter_moneyflow_created_and_more'), ('finances', '0007_alter_category_type_alter_category_user_and_more')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='category_types', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Category type',
                'verbose_name_plural': 'Category types',
            },
        ),
        migrations.CreateModel(
            name='MoneyFlowStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='money_flow_statuses', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Money flow status',
                'verbose_name_plural': 'Money flow statuses',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Children', to='finances.category', verbose_name='Parent category')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='categories', to='finances.categorytype', verbose_name='Type')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='categories', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='MoneyFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('total_sum', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000000)], verbose_name='Total sum')),
                ('comment', models.TextField(blank=True, max_length=500, null=True, verbose_name='Comment')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='money_flows', to='finances.category', verbose_name='Category')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='money_flows', to='finances.moneyflowstatus', verbose_name='Status')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='money_flows', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Money flow',
                'verbose_name_plural': 'Money flows',
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('title', 'user'), name='unique_category_per_user'),
        ),
        migrations.AddConstraint(
            model_name='categorytype',
            constraint=models.UniqueConstraint(fields=('title', 'user'), name='unique_category_type_per_user'),
        ),
        migrations.AddConstraint(
            model_name='moneyflowstatus',
            constraint=models.UniqueConstraint(fields=('title', 'user'), name='unique_money_flow_status_per_user'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Children', to='finances.category', verbose_name='Parent category'),
        ),
        migrations.AlterField(
            model_name='moneyflow',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='moneyflow',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000000)], verbose_name='Total sum'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='finances.categorytype', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='category',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='categorytype',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_types', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='moneyflow',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_flows', to='finances.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='moneyflow',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_flows', to='finances.moneyflowstatus', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='moneyflow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_flows', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='moneyflowstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_flow_statuses', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
