# Generated by Django 5.1.1 on 2025-07-25 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_moneyflow_status_moneyflow_user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_parent_slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
