# Generated by Django 5.1.1 on 2025-07-25 22:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_category_user_categorytype_user_moneyflowstatus_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='categorytype',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='moneyflowstatus',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Title'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('title', 'user'), name='unique_category_per_user'),
        ),
        migrations.AddConstraint(
            model_name='categorytype',
            constraint=models.UniqueConstraint(fields=('title', 'user'), name='unique_category_type_per_user'),
        ),
        migrations.AddConstraint(
            model_name='moneyflowstatus',
            constraint=models.UniqueConstraint(fields=('title', 'user'), name='unique_money_flow_status_per_user'),
        ),
    ]
