# Generated by Django 5.1.1 on 2025-07-26 14:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_alter_category_title_alter_categorytype_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Children', to='finances.category', verbose_name='Parent category'),
        ),
        migrations.AlterField(
            model_name='moneyflow',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='moneyflow',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000000)], verbose_name='Total sum'),
        ),
    ]
